# -*- coding: utf-8 -*-
"""projeto_integrador 2_2004.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1IAgunkbcyjVzKSEksJEeIl447oKrmi

###RAFAEL AUGUSTO MORAES MONTEIRO - 3 TERMO CD FATEC/OURINHOS.###

## ESTRUTURA SEQUENCIAL ##
"""

#1

n = int(input('Digite um número INTEIRO: '))

print (f'O ANTECESSOR do número {n} é o número {n-1}')
print (f'O SUCESSOR do número {n} é número {n+1}')

#2

pol = float(input('Digite o valor em POLEGADAS: '))

cen = pol*2.54

print (f'O valor de {pol} polegadas equivale a {cen}')

#3

custofabrica = float(input('Digite o valor de CUSTO do carro em R$: '))

valorfinal = (custofabrica + (custofabrica*0.28) + (custofabrica*0.45))

print (f'O valor final do veículo, que tem custo de R$ {custofabrica} na fábrica, é de R$ {valorfinal}')

"""## ESTRUTURA DE SELEÇÃO ##"""

#1

n1 = int(input('Digite um valor INTEIRO: '))
n2 = int(input('Digite outro valor INTEIRO: '))

if n1 == n2:
  print ('Os valores são iguais.')
else:
  print ('Os valores são diferentes.')

#2

maca = int(input('Digite quantas maçãs deseja comprar: '))

if maca <= 11:
  print (f'Sua compra de {maca} maçãs fica no total de R$ {maca*1.3}')
else:
  print (f'Sua compra de {maca} maçãs fica no total de R$ {maca*1}')

#3

valortotal = float(input('Digite o valor total da compra em R$: '))

while True:
  print ('Qual tipo de cliente você é? Digite o index.')
  print ('1 - CLIENTE COMUM.')
  print ('2 - FUNCIONÁRIO.')
  print ('3 - VIP.')

  opcao = input('Digite o index: ')

  if opcao == '1':
    print (f'O valor da sua compra é de R$ {valortotal}.')
    break
  elif opcao == '2':
    opcao2 = (valortotal*0.9)
    print (f'O valor da sua compra de R$ {valortotal}, adcionado 10% de desconto por ser funcionário, resulta em R$ {opcao2}.')
    break
  elif opcao == '3':
    opcao3 = (valortotal*0.95)
    print (f'O valor da sua compra de R$ {valortotal}, adcionado 5% de desconto por ser cliente vip, resulta em R$ {opcao3}.')
    break

#4

p1 = float(input('Digite a nota da p1: '))
p2 = float(input('Digite a nota da p2: '))

media = (p1+p2)/2

if media < 6:
  print (f'Sua média foi de {media}, portanto está REPROVADO.')
else:
  print (f'Sua média foi de {media}, portanto está APROVADO.')

#5

idade = int(input('Digite a idade do nadador: '))

if idade >= 5 and idade <= 7:
  print ('O nadador está enquadrado na categoria INFANTIL A.')
elif idade >= 8 and idade <= 10:
  print ('O nadador está enquadrado na categoria INFANTIL B.')
elif idade >= 11 and idade <= 13:
  print ('O nadador está enquadrado na categoria JUNIVEL A.')
elif idade >= 14 and idade <= 17:
  print ('O nadador está enquadrado na categoria JUNIVEL B.')
elif idade >= 18:
  print ('O nadador está enquadrado na categoria ADULTO.')
else:
  print ('Inválido.')

#6

alcool = 2.90
gasolina = 3.30

qtdlitro = float(input('Digite o valor em LITROS vendidos: '))

while True:
  print ('Tipo de combustível:')
  print ('1 - ÁLCOOL.')
  print ('2 - GASOLINA.')

  opcao = input('Digite o index: ')

  if opcao == '1':
    if qtdlitro <= 20:
      print (f'O valor a ser pago, com 3% de desconto por litro, será de R$ {qtdlitro*(alcool*0.97):.2f}')
      break
    elif qtdlitro > 20:
      print (f'O valor a ser pago, com 5% de desconto por litro, será de R$ {qtdlitro*(alcool*0.95):.2f}')
      break
  elif opcao =='2':
    if qtdlitro <= 20:
      print (f'O valor a ser pago, com 4% de desconto por litro, será de R$ {qtdlitro*(gasolina*0.96):.2f}')
      break
    elif qtdlitro > 20:
      print (f'O valor a ser pago, com 6% de desconto por litro, será de R$ {qtdlitro*(gasolina*0.94):.2f}')
      break

"""##ESTRUTURA DE REPETIÇÃO##"""

#1

for i in range (1, 51):
  print (i)

#2

for i in range (1, 39):
  if i % 2 == 0:
    print (i)

#3

n1 = int(input('Digite o primeiro valor: '))
n2 = int(input('Digite o segundo valor: '))

soma = 0

for i in range (n1, n2+1):
  soma += i
print (f'A soma dos valores {n1} e {n2} é igual a {soma}.')

#4
lista = []

item = input(f'Digite o nome do item {1}: ')
preco = float(input(f'Digite o preço do item {1}: '))
lista.append(preco)

maior_preco = preco
soma_precos = preco

for i in range(1, 15):
    item = input(f'Digite o nome do item {i+1}: ')
    preco = float(input(f'Digite o preço do item {i+1}: '))
    lista.append(preco)

    if preco > maior_preco:
        maior_preco = preco

    soma_precos += preco

media_precos = soma_precos / 15

print(f'O maior preço lido foi de R$ {maior_preco}.')
print(f'A média aritmética dos preços dos produtos é de R$ {media_precos:.2f}.')

#5

chico_alt = 1.5
juca_alt = 1.1
anos = 0

while chico_alt > juca_alt:
  chico_alt += 0.02
  juca_alt += 0.03
  anos += 1

print(f'Serão necessários {anos} anos para que Juca seja maior que Chico.')

#6

n = int(input('Digite um valor INTEIRO e POSITIVO: '))
fat = 1

if n == 0:
  print(f'O fatorial de {n} é 1.')
else:
  for i in range(1, n + 1):
    fat *= i
  print(f'O fatorial de {n} é {fat}.')

"""##VETORES##"""

#1

vetores = []

for i in range(10):
  valor = int(input('Digite o valor do vetor: '))
  vetores.append(valor)

for i in vetores:
  if i % 2 != 0:
    print(i)

#2

vetores = []

for i in range(6):
  valor = float(input('Digite o valor do vetor: '))
  vetores.append(valor)

media = sum(vetores) / len(vetores)
maior_valor = max(vetores)
menor_valor = min(vetores)

print(f'A média dos vetores é de {media}.')
print(f'O maior vetor é {maior_valor}.')
print(f'O menor vetor é {menor_valor}.')

#3

vetor = []
for i in range(10):
  valor = int(input(f'Digite o valor INTEIRO da posição {i} do vetor principal: '))
  vetor.append(valor)

vetor_trasfrente = []
for i in range(len(vetor)-1, -1, -1):
  vetor_trasfrente.append(vetor[i])

print(f'Vetor principal: {vetor}')
print(f'Vetor de trás para frente: {vetor_trasfrente}')

#4

vetor = []
soma = 0

for i in range(10):
    valor = int(input(f'Digite o valor da posição {i} do vetor: '))
    vetor.append(valor)

for i in range(0, 10, 2):
    if vetor[i] > 0:
        soma += vetor[i]

print(f'A soma dos elementos positivos que se encontram nas posições pares do vetor é de: {soma}')